package com.moviecatalog.core.designsystem.tokens.color

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class MovieSemanticColors(
    val contentHigh: Color,
    val contentMedium: Color,
    val contentLow: Color,
    val contentDisabled: Color,
    val contentBrand: Color,
    val contentOnBrandHigh: Color,
    val contentOnBrandMedium: Color,
    val contentOnBrandLow: Color,
    val backgroundBody: Color,
    val backgroundSurface: Color,
    val backgroundSurfaceHover: Color,
    val backgroundNeutralSubtle: Color,
    val backgroundNeutralSubtleHover: Color,
    val backgroundBrand: Color,
    val backgroundBrandHover: Color,
    val backgroundBrandSubtle: Color,
    val backgroundBrandSubtleHover: Color,
    val borderHigh: Color,
    val borderMedium: Color,
    val borderLow: Color,
    val contentPositive: Color,
    val contentNegative: Color,
    val contentWarning: Color,
    val contentInfo: Color,
    val backgroundPositiveSubtle: Color,
    val backgroundPositiveSubtleHover: Color,
    val backgroundNegativeSubtle: Color,
    val backgroundNegativeSubtleHover: Color,
    val backgroundWarningSubtle: Color,
    val backgroundWarningSubtleHover: Color,
    val backgroundInfoSubtle: Color,
    val backgroundInfoSubtleHover: Color,
    val buttonNeutralEnabledBackground: Color,
    val buttonNeutralDisabledBackground: Color,
    val buttonDestructiveEnabledBackground: Color,
    val buttonDestructiveDisabledBackground: Color,
    val buttonPrimaryDisabledBackground: Color,
    val buttonDestructiveContent: Color,
) {
    companion object {
        fun darkDefault(): MovieSemanticColors {
            val p = MovieColorPrimitives
            return MovieSemanticColors(
                contentHigh = Color(0xFFF5F5F5),
                contentMedium = Color(0xFFA3A3A3),
                contentLow = Color(0xFF737373),
                contentDisabled = Color(0xFF525252),
                contentBrand = p.Primary,
                contentOnBrandHigh = Color(0xFFFFFFFF),
                contentOnBrandMedium = Color(0xE6FFFFFF),
                contentOnBrandLow = Color(0xB3FFFFFF),
                backgroundBody = p.Surface,
                backgroundSurface = p.SurfaceContainer,
                backgroundSurfaceHover = p.SurfaceBright,
                backgroundNeutralSubtle = p.SurfaceContainer,
                backgroundNeutralSubtleHover = p.SurfaceBright,
                backgroundBrand = p.Primary,
                backgroundBrandHover = Color(0xFFFF1A26),
                backgroundBrandSubtle = Color(0x33E50914),
                backgroundBrandSubtleHover = Color(0x4DE50914),
                borderHigh = p.NeutralFill,
                borderMedium = p.SurfaceBright,
                borderLow = Color(0xFF1F1F1F),
                contentPositive = p.Secondary,
                contentNegative = p.Error,
                contentWarning = Color(0xFFFFB547),
                contentInfo = p.Tertiary,
                backgroundPositiveSubtle = Color(0x3345FEC9),
                backgroundPositiveSubtleHover = Color(0x4D45FEC9),
                backgroundNegativeSubtle = Color(0x33FF6E84),
                backgroundNegativeSubtleHover = Color(0x4DFF6E84),
                backgroundWarningSubtle = Color(0x33FFB547),
                backgroundWarningSubtleHover = Color(0x4DFFB547),
                backgroundInfoSubtle = Color(0x33D7A0FF),
                backgroundInfoSubtleHover = Color(0x4DD7A0FF),
                buttonNeutralEnabledBackground = p.NeutralFill,
                buttonNeutralDisabledBackground = p.NeutralFillDisabled,
                buttonDestructiveEnabledBackground = p.DestructiveFill,
                buttonDestructiveDisabledBackground = p.DestructiveFillDisabled,
                buttonPrimaryDisabledBackground = p.BrandFillDisabled,
                buttonDestructiveContent = p.InkOnSaturated,
            )
        }
    }
}