name: Build development quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

defaults:
  run:
    shell: bash

jobs:

  detekt:
    name: Detekt
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run Detekt
        uses: ./.github/actions/gradle-check/action.yaml
        with:
          gradle-args: detekt

      - name: Upload SARIF (Detekt)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '**/build/reports/detekt/detekt.sarif'

      - name: Reviewdog (Detekt PR comments)
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-sarif@v1
        with:
          sarif_file: '**/build/reports/detekt/detekt.sarif'
          reporter: github-pr-review
          fail_on_error: true


  ktlint:
    name: KtLint
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run KtLint
        uses: ./.github/actions/gradle-check/action.yaml/
        with:
          gradle-args: ktlintCheck


  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run all tests
        uses: ./.github/actions/gradle-check/action.yaml/
        with:
          gradle-args: allTests